/**
 * Portions of this software was developed by employees of the National Institute
 * of Standards and Technology (NIST), an agency of the Federal Government and is
 * being made available as a public service. Pursuant to title 17 United States
 * Code Section 105, works of NIST employees are not subject to copyright
 * protection in the United States. This software may be subject to foreign
 * copyright. Permission in the United States and in foreign countries, to the
 * extent that NIST may hold copyright, to use, copy, modify, create derivative
 * works, and distribute this software and its documentation without fee is hereby
 * granted on a non-exclusive basis, provided that this notice and disclaimer
 * of warranty appears in all copies.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS' WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND FREEDOM FROM
 * INFRINGEMENT, AND ANY WARRANTY THAT THE DOCUMENTATION WILL CONFORM TO THE
 * SOFTWARE, OR ANY WARRANTY THAT THE SOFTWARE WILL BE ERROR FREE.  IN NO EVENT
 * SHALL NIST BE LIABLE FOR ANY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DIRECT,
 * INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM,
 * OR IN ANY WAY CONNECTED WITH THIS SOFTWARE, WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT, OR OTHERWISE, WHETHER OR NOT INJURY WAS SUSTAINED BY PERSONS OR
 * PROPERTY OR OTHERWISE, AND WHETHER OR NOT LOSS WAS SUSTAINED FROM, OR AROSE OUT
 * OF THE RESULTS OF, OR USE OF, THE SOFTWARE OR SERVICES PROVIDED HEREUNDER.
 */
//

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 03:42:10 PM PST 
//

package gov.nist.secautotrust.tmsad.input;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the gov.nist.scap.tmsad.input package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
   * package: gov.nist.scap.tmsad.input
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Signs }
   * 
   */
  public Signs createSigns() {
    return new Signs();
  }

  /**
   * Create an instance of {@link Sign.KeyInfo }
   * 
   */
  public Sign.KeyInfo createSignKeyInfo() {
    return new Sign.KeyInfo();
  }

  /**
   * Create an instance of {@link Sign.Insert }
   * 
   */
  public Sign.Insert createSignInsert() {
    return new Sign.Insert();
  }

  /**
   * Create an instance of {@link Signs.XpathNamespacePrefixMap.Ns }
   * 
   */
  public Signs.XpathNamespacePrefixMap.Ns createSignsXpathNamespacePrefixMapNs() {
    return new Signs.XpathNamespacePrefixMap.Ns();
  }

  /**
   * Create an instance of {@link Sign }
   * 
   */
  public Sign createSign() {
    return new Sign();
  }

  /**
   * Create an instance of {@link Sign.Manifest }
   * 
   */
  public Sign.Manifest createSignManifest() {
    return new Sign.Manifest();
  }

  /**
   * Create an instance of {@link Sign.SignatureProperty }
   * 
   */
  public Sign.SignatureProperty createSignSignatureProperty() {
    return new Sign.SignatureProperty();
  }

  /**
   * Create an instance of {@link Reference }
   *
   */
  public Reference createReference() {
    return new Reference();
  }

  /**
   * Create an instance of {@link Signs.XpathNamespacePrefixMap }
   *
   */
  public Signs.XpathNamespacePrefixMap createSignsXpathNamespacePrefixMap() {
    return new Signs.XpathNamespacePrefixMap();
  }

  /**
   * Create an instance of {@link Reference.Xpath }
   *
   */
  public Reference.Xpath createReferenceXpath() {
    return new Reference.Xpath();
  }

}
