/**
 * Portions of this software was developed by employees of the National Institute
 * of Standards and Technology (NIST), an agency of the Federal Government and is
 * being made available as a public service. Pursuant to title 17 United States
 * Code Section 105, works of NIST employees are not subject to copyright
 * protection in the United States. This software may be subject to foreign
 * copyright. Permission in the United States and in foreign countries, to the
 * extent that NIST may hold copyright, to use, copy, modify, create derivative
 * works, and distribute this software and its documentation without fee is hereby
 * granted on a non-exclusive basis, provided that this notice and disclaimer
 * of warranty appears in all copies.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS' WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND FREEDOM FROM
 * INFRINGEMENT, AND ANY WARRANTY THAT THE DOCUMENTATION WILL CONFORM TO THE
 * SOFTWARE, OR ANY WARRANTY THAT THE SOFTWARE WILL BE ERROR FREE.  IN NO EVENT
 * SHALL NIST BE LIABLE FOR ANY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DIRECT,
 * INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM,
 * OR IN ANY WAY CONNECTED WITH THIS SOFTWARE, WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT, OR OTHERWISE, WHETHER OR NOT INJURY WAS SUSTAINED BY PERSONS OR
 * PROPERTY OR OTHERWISE, AND WHETHER OR NOT LOSS WAS SUSTAINED FROM, OR AROSE OUT
 * OF THE RESULTS OF, OR USE OF, THE SOFTWARE OR SERVICES PROVIDED HEREUNDER.
 */
//

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 03:42:10 PM PST 
//

package gov.nist.secautotrust.tmsad.input;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://scap.nist.gov/tmsad/input}sign" maxOccurs="unbounded"/>
 *         &lt;element name="xpath-namespace-prefix-map" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ns" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="output-file" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="source-file" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sign", "xpathNamespacePrefixMap" })
@XmlRootElement(name = "signs")
public class Signs {

  @XmlElement(required = true)
  protected List<Sign> sign;
  @XmlElement(name = "xpath-namespace-prefix-map")
  protected Signs.XpathNamespacePrefixMap xpathNamespacePrefixMap;
  @XmlAttribute(name = "output-file", required = true)
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  @XmlSchemaType(name = "normalizedString")
  protected String outputFile;
  @XmlAttribute(name = "source-file")
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  @XmlSchemaType(name = "normalizedString")
  protected String sourceFile;

  /**
   * Gets the value of the sign property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the sign property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getSign().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Sign }
   *
   *
   */
  public List<Sign> getSign() {
    if (sign == null) {
      sign = new ArrayList<Sign>();
    }
    return this.sign;
  }

  /**
   * Gets the value of the xpathNamespacePrefixMap property.
   *
   * @return possible object is {@link Signs.XpathNamespacePrefixMap }
   *
   */
  public Signs.XpathNamespacePrefixMap getXpathNamespacePrefixMap() {
    return xpathNamespacePrefixMap;
  }

  /**
   * Sets the value of the xpathNamespacePrefixMap property.
   *
   * @param value
   *          allowed object is {@link Signs.XpathNamespacePrefixMap }
   *
   */
  public void setXpathNamespacePrefixMap(Signs.XpathNamespacePrefixMap value) {
    this.xpathNamespacePrefixMap = value;
  }

  /**
   * Gets the value of the outputFile property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getOutputFile() {
    return outputFile;
  }

  /**
   * Sets the value of the outputFile property.
   *
   * @param value
   *          allowed object is {@link String }
   *
   */
  public void setOutputFile(String value) {
    this.outputFile = value;
  }

  /**
   * Gets the value of the sourceFile property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getSourceFile() {
    return sourceFile;
  }

  /**
   * Sets the value of the sourceFile property.
   *
   * @param value
   *          allowed object is {@link String }
   *
   */
  public void setSourceFile(String value) {
    this.sourceFile = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   *
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="ns" maxOccurs="unbounded">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
   *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   *
   *
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "ns" })
  public static class XpathNamespacePrefixMap {

    @XmlElement(required = true)
    protected List<Signs.XpathNamespacePrefixMap.Ns> ns;

    /**
     * Gets the value of the ns property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is why
     * there is not a <CODE>set</CODE> method for the ns property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getNs().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Signs.XpathNamespacePrefixMap.Ns }
     *
     *
     */
    public List<Signs.XpathNamespacePrefixMap.Ns> getNs() {
      if (ns == null) {
        ns = new ArrayList<Signs.XpathNamespacePrefixMap.Ns>();
      }
      return this.ns;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ns {

      @XmlAttribute(required = true)
      @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
      @XmlSchemaType(name = "token")
      protected String prefix;
      @XmlAttribute(required = true)
      @XmlSchemaType(name = "anyURI")
      protected String uri;

      /**
       * Gets the value of the prefix property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getPrefix() {
        return prefix;
      }

      /**
       * Sets the value of the prefix property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setPrefix(String value) {
        this.prefix = value;
      }

      /**
       * Gets the value of the uri property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getUri() {
        return uri;
      }

      /**
       * Sets the value of the uri property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setUri(String value) {
        this.uri = value;
      }

    }

  }

}
